#!/bin/sh

set -e

RAGOLATION_LANGUAGE_DIR="$(realpath $(dirname $0))"
PRYBAR_ROOT_DIR="$(dirname $(dirname "${RAGOLATION_LANGUAGE_DIR}"))"

cd "${PRYBAR_ROOT_DIR}/prybar_assets/ragolation" && HOME="" rag inst
